// THIS FILE IS AUTOGENERATED
// DO NOT MODIFY USE: yarn icons

import React, { useMemo, CSSProperties } from "react";

const IconSendMessage = ({
  className,
  tintColor,
  style,
}: {
  className?: string;
  tintColor?: string;
  style?: CSSProperties;
}) => {
  const combinedStyle: Object = useMemo(
    () => ({
      ...(tintColor
        ? { color: tintColor, flexShrink: 0, pointerEvents: "none" }
        : { color: "#4F4F5C", flexShrink: 0, pointerEvents: "none" }),
      ...(style || {}),
    }),
    [tintColor, style]
  );

  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      style={combinedStyle}
      width="24px"
      height="24px"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M17.066 5.496l-.826 1.481-3.155-1.76.826-1.482a.216.216 0 01.294-.083l2.777 1.55c.105.058.142.19.084.294zM6.991 16.661l2.726 1.522L6.9 20.137l.091-3.476zm3.42.763l-3.156-1.76 5.342-9.574 3.156 1.76-5.342 9.574zM17.47 4.33l-2.777-1.55a1.216 1.216 0 00-1.654.47L6.072 15.732a.507.507 0 00-.064.23l-.133 5.133a.499.499 0 00.785.424l4.162-2.886a.507.507 0 00.151-.168l.056-.099c.004-.007.012-.01.016-.017.004-.009.004-.019.01-.029l5.804-10.4c.004-.008.011-.01.015-.017.005-.009.005-.018.008-.027l1.057-1.894a1.218 1.218 0 00-.47-1.654z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
};

export { IconSendMessage };
