// THIS FILE IS AUTOGENERATED
// DO NOT MODIFY USE: yarn icons

import React, { useMemo, CSSProperties } from "react";

const IconClose = ({
  className,
  tintColor,
  style,
}: {
  className?: string;
  tintColor?: string;
  style?: CSSProperties;
}) => {
  const combinedStyle: Object = useMemo(
    () => ({
      ...(tintColor
        ? { color: tintColor, flexShrink: 0, pointerEvents: "none" }
        : { color: "#AEAEB9", flexShrink: 0, pointerEvents: "none" }),
      ...(style || {}),
    }),
    [tintColor, style]
  );

  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      style={combinedStyle}
      width="24px"
      height="24px"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M18.481 4.598a.336.336 0 00-.475 0L12 10.604 5.994 4.598a.336.336 0 00-.475 0l-.92.921a.336.336 0 000 .475L10.603 12l-6.006 6.007a.336.336 0 000 .475l.921.921a.336.336 0 00.475 0L12 13.396l6.006 6.007c.131.131.343.131.475 0l.921-.92a.336.336 0 000-.476L13.396 12l6.006-6.006a.336.336 0 000-.475l-.92-.92z"
        fill="currentColor"
      />
    </svg>
  );
};

export { IconClose };
