// THIS FILE IS AUTOGENERATED
// DO NOT MODIFY USE: yarn icons

import React, { useMemo, CSSProperties } from "react";

const IconSettings = ({
  className,
  tintColor,
  style,
}: {
  className?: string;
  tintColor?: string;
  style?: CSSProperties;
}) => {
  const combinedStyle: Object = useMemo(
    () => ({
      ...(tintColor
        ? { color: tintColor, flexShrink: 0, pointerEvents: "none" }
        : { color: "#93939A", flexShrink: 0, pointerEvents: "none" }),
      ...(style || {}),
    }),
    [tintColor, style]
  );

  return (
    <svg
      className={className}
      viewBox="0 0 20 20"
      style={combinedStyle}
      width="20px"
      height="20px"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M7.756 3.466L8.325 1h3.349l.569 2.466c.271.093.536.202.791.327l2.145-1.341 2.368 2.368-1.341 2.145c.125.254.234.52.327.791l2.466.569v3.349l-2.466.569a6.85 6.85 0 01-.327.791l1.341 2.145-2.368 2.368-2.145-1.341c-.254.125-.52.234-.791.327l-.569 2.466H8.325l-.569-2.466a6.85 6.85 0 01-.791-.327L4.82 17.547l-2.368-2.368 1.341-2.145a6.777 6.777 0 01-.327-.791L1 11.674V8.325l2.466-.569a6.85 6.85 0 01.327-.791L2.452 4.82 4.82 2.452l2.145 1.341c.254-.125.52-.234.791-.327zM14.185 10a4.186 4.186 0 10-8.372 0 4.186 4.186 0 008.372 0z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
};

export { IconSettings };
